#!/usr/bin/env python3
"""
build_photos.py — render photos.json into the web global photos.js.

photos.json is the source of truth for the website's photo galleries
(currently the Pearl Harbor shipmate snapshots). This emits photos.js
(`window.PHOTOS = {...}`), mirroring scripts/build_cast.py and weather.js.

Usage:
    python3 scripts/build_photos.py          # writes photos.js
    python3 scripts/build_photos.py --check  # validate only (every image exists)

No third-party dependencies. Paths resolve relative to the repo root.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PHOTOS_JSON = REPO / "photos.json"
PHOTOS_JS = REPO / "photos.js"


def load() -> dict:
    if not PHOTOS_JSON.exists():
        sys.stderr.write(f"photos.json not found at {PHOTOS_JSON}.\n")
        sys.exit(2)
    with PHOTOS_JSON.open(encoding="utf-8") as fh:
        return json.load(fh)


def validate(data: dict) -> list[str]:
    problems: list[str] = []
    for gal in data.get("galleries", []):
        if not gal.get("items"):
            problems.append(f"gallery '{gal.get('id')}' has no items")
        for it in gal.get("items", []):
            for key in ("front", "back"):
                rel = it.get(key)
                if rel and not (REPO / rel).exists():
                    problems.append(f"{it.get('id')}: missing image {rel}")
            if not it.get("front"):
                problems.append(f"{it.get('id')}: no front image")
    return problems


def emit(data: dict) -> None:
    body = json.dumps(data, ensure_ascii=False, indent=2)
    PHOTOS_JS.write_text(
        "// Generated by scripts/build_photos.py from photos.json — do not edit by hand.\n"
        "// Photo galleries (Gene and shipmates at Pearl Harbor). Consumed by\n"
        "// app.jsx via window.PHOTOS.\n"
        f"window.PHOTOS = {body};\n",
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="Validate only; write nothing.")
    args = ap.parse_args()

    data = load()
    problems = validate(data)
    if problems:
        sys.stderr.write("photos.json validation problems:\n")
        for pr in problems:
            sys.stderr.write(f"  - {pr}\n")
        return 1

    if args.check:
        n = sum(len(g.get("items", [])) for g in data.get("galleries", []))
        print(f"photos.json OK: {len(data.get('galleries', []))} gallery(ies), {n} photos.")
        return 0

    emit(data)
    n = sum(len(g.get("items", [])) for g in data.get("galleries", []))
    print(f"Wrote {PHOTOS_JS.relative_to(REPO)} ({n} photos).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
