#!/usr/bin/env python3
"""
build_letters.py — regenerate letters.js from letters.json + chapters.json.

letters.json (the array of letter records) and chapters.json are the editable
source of truth for the website's letter data. This emits letters.js, which the
site loads as `window.LETTERS` / `window.CHAPTERS`. Mirrors scripts/build_cast.py
and build_photos.py.

Do not hand-edit letters.js; edit the letters in the editor (Edit Letters.command)
or in letters.json, then run this. Usage:

    python3 scripts/build_letters.py            # writes letters.js
    python3 scripts/build_letters.py --check    # validate only (no write)

No third-party dependencies. Paths resolve relative to the repo root.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LETTERS_JSON = REPO / "letters.json"
CHAPTERS_JSON = REPO / "chapters.json"
LETTERS_JS = REPO / "letters.js"


def load(path: Path):
    if not path.exists():
        sys.stderr.write(f"{path.name} not found at {path}.\n")
        sys.exit(2)
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def validate(letters, chapters) -> list[str]:
    problems: list[str] = []
    if not isinstance(letters, list) or not letters:
        problems.append("letters.json is not a non-empty array")
        return problems
    if not isinstance(chapters, list) or not chapters:
        problems.append("chapters.json is not a non-empty array")
    chapter_keys = {c.get("key") for c in chapters if isinstance(c, dict)}
    seen_ids = set()
    for i, l in enumerate(letters):
        if not isinstance(l, dict):
            problems.append(f"letter #{i} is not an object")
            continue
        lid = l.get("id", f"<#{i}>")
        if not l.get("id"):
            problems.append(f"letter #{i} has no id")
        if lid in seen_ids:
            problems.append(f"duplicate letter id {lid}")
        seen_ids.add(lid)
        if not l.get("body") and l.get("status") not in (
            "envelope_only", "telegram", "christmas_card"
        ):
            problems.append(f"{lid}: empty body for status {l.get('status')}")
        if l.get("location_chapter") and chapter_keys and l["location_chapter"] not in chapter_keys:
            problems.append(f"{lid}: unknown location_chapter '{l['location_chapter']}'")
    return problems


def render(letters, chapters) -> str:
    """The exact text of letters.js for the given data (used by emit + sync checks)."""
    letters_js = json.dumps(letters, ensure_ascii=False, indent=2)
    chapters_js = json.dumps(chapters, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/build_letters.py from letters.json + chapters.json.\n"
        "// DO NOT EDIT BY HAND. Edit a letter in the editor (double-click\n"
        "// 'Edit Letters.command') or edit letters.json, then run build_letters.py.\n"
        f"window.LETTERS = {letters_js};\n\n"
        f"window.CHAPTERS = {chapters_js};\n"
    )


def emit(letters, chapters) -> None:
    LETTERS_JS.write_text(render(letters, chapters), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="Validate only; write nothing.")
    args = ap.parse_args()

    letters = load(LETTERS_JSON)
    chapters = load(CHAPTERS_JSON)
    problems = validate(letters, chapters)
    if problems:
        sys.stderr.write("letters.json validation problems:\n")
        for pr in problems:
            sys.stderr.write(f"  - {pr}\n")
        return 1

    if args.check:
        print(f"OK: {len(letters)} letters, {len(chapters)} chapters.")
        return 0

    emit(letters, chapters)
    print(f"Wrote {LETTERS_JS.relative_to(REPO)} ({len(letters)} letters, {len(chapters)} chapters).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
