#!/usr/bin/env python3
"""
build_cast.py — render cast.json into the web global (cast.js) and the
museum packet document (museum/cast-of-characters.md).

cast.json is the single source of truth for the "cast of characters" the
National WWII Museum asked for: everyone mentioned across the letters and
their relation to the writer. The book pipeline (book/build_book.py) renders
the same cast.json into LaTeX; this script handles the website and the
human-readable museum copy.

Usage:
    python3 scripts/build_cast.py            # writes cast.js + museum/cast-of-characters.md
    python3 scripts/build_cast.py --check    # validate only, write nothing

Run from anywhere; paths resolve relative to the repo root (parent of scripts/).
No third-party dependencies.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CAST_JSON = REPO / "cast.json"
CAST_JS = REPO / "cast.js"
MUSEUM_MD = REPO / "museum" / "cast-of-characters.md"

WRITER = 'Raymond Eugene "Gene" Lankford'
RECIPIENT = "Joan Northcutt"


def load_cast() -> dict:
    if not CAST_JSON.exists():
        sys.stderr.write(
            f"cast.json not found at {CAST_JSON}.\n"
            "Run the cast-extraction step first (it produces the roster).\n"
        )
        sys.exit(2)
    with CAST_JSON.open(encoding="utf-8") as fh:
        return json.load(fh)


def group_members(cast: dict, key: str) -> list[dict]:
    members = [p for p in cast.get("people", []) if p.get("group") == key]
    members.sort(key=lambda p: (p.get("sort") or p.get("name") or "").lower())
    return members


def emit_castjs(cast: dict) -> None:
    body = json.dumps(cast, ensure_ascii=False, indent=2)
    CAST_JS.write_text(
        "// Generated by scripts/build_cast.py from cast.json — do not edit by hand.\n"
        "// The roster of people mentioned across the letters (the museum's\n"
        '// "cast of characters"). Consumed by app.jsx via window.CAST.\n'
        f"window.CAST = {body};\n",
        encoding="utf-8",
    )


def fmt_letters(person: dict) -> str:
    ids = person.get("letters") or []
    if not ids:
        return ""
    n = len(ids)
    listing = ", ".join(ids)
    suffix = "letter" if n == 1 else "letters"
    return f"Appears in {n} {suffix}: {listing}"


def emit_museum_md(cast: dict) -> None:
    MUSEUM_MD.parent.mkdir(parents=True, exist_ok=True)
    out: list[str] = []
    out.append("# Cast of Characters")
    out.append("")
    out.append(
        f"The people mentioned throughout the wartime letters of {WRITER} "
        f"to {RECIPIENT}, and their relation to the writer. Prepared for "
        "The National WWII Museum as donor-provided interpretive material."
    )
    out.append("")
    out.append(
        "_Identifications are drawn from the letters themselves and from "
        "family research. Entries marked (uncertain) rest on an ambiguous "
        "reading or an inferred relationship._"
    )
    out.append("")
    total = len(cast.get("people", []))
    out.append(f"_{total} people across {len(cast.get('groups', []))} groupings._")
    out.append("")

    for group in cast.get("groups", []):
        members = group_members(cast, group["key"])
        if not members:
            continue
        out.append(f"## {group['label']}")
        if group.get("blurb"):
            out.append("")
            out.append(f"_{group['blurb']}_")
        out.append("")
        for p in members:
            name = p.get("name", "")
            relation = p.get("relation", "")
            head = f"**{name}**"
            if relation:
                head += f" — {relation}"
            if p.get("uncertain"):
                head += " _(uncertain)_"
            out.append(head)
            if p.get("bio"):
                out.append("")
                out.append(p["bio"])
            refs = fmt_letters(p)
            if refs:
                out.append("")
                out.append(f"_{refs}_")
            if p.get("note"):
                out.append("")
                out.append(f"Note: {p['note']}")
            out.append("")
        out.append("")

    MUSEUM_MD.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")


def validate(cast: dict) -> list[str]:
    """Return a list of problems; empty means valid."""
    problems: list[str] = []

    group_keys = {g.get("key") for g in cast.get("groups", [])}
    if not group_keys:
        problems.append("cast.json has no groups.")

    valid_ids = {
        f.name.split("_", 1)[0]
        for f in REPO.iterdir()
        if f.is_dir() and f.name.startswith("L") and "_" in f.name
    }

    seen_ids: set[str] = set()
    for p in cast.get("people", []):
        pid = p.get("id", "<missing id>")
        if pid in seen_ids:
            problems.append(f"Duplicate person id: {pid}")
        seen_ids.add(pid)

        if p.get("group") not in group_keys:
            problems.append(f"{pid}: unknown group '{p.get('group')}'")

        if p.get("group") != "principals" and not p.get("aliases"):
            problems.append(f"{pid}: no aliases (needed to locate them in letters)")

        for lid in p.get("letters", []):
            if lid not in valid_ids:
                problems.append(f"{pid}: references unknown letter '{lid}'")

    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="Validate only; write nothing.")
    args = ap.parse_args()

    cast = load_cast()
    problems = validate(cast)
    if problems:
        sys.stderr.write("cast.json validation problems:\n")
        for pr in problems:
            sys.stderr.write(f"  - {pr}\n")
        if args.check:
            return 1
        sys.stderr.write("Refusing to render an invalid cast. Fix the above.\n")
        return 1

    if args.check:
        print(f"cast.json OK: {len(cast.get('people', []))} people, "
              f"{len(cast.get('groups', []))} groups.")
        return 0

    emit_castjs(cast)
    emit_museum_md(cast)
    print(f"Wrote {CAST_JS.relative_to(REPO)} and {MUSEUM_MD.relative_to(REPO)} "
          f"({len(cast.get('people', []))} people).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
