// Fetches historical weather for every letter date+location from Open-Meteo's
// free archive API (which goes back to 1940), then writes ../weather.js with a
// window.LETTER_WEATHER map keyed by letter id.
//
//   Usage:    node scripts/fetch_weather.mjs
//   Requires: Node 18+ (built-in fetch).
//
// Open-Meteo is free and unauthenticated. If the script is rerun it will
// overwrite weather.js. To re-do a single letter, edit weather.js by hand
// or rerun the whole script.

import fs from "node:fs/promises";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// Coordinates per location_chapter. Open-Meteo has 1940-era reanalysis at
// ~10km resolution; these are the nearest reasonable coordinates for each.
const LOCATIONS = {
  "great-lakes":  { lat: 42.31, lon: -87.84, tz: "America/Chicago"     }, // Great Lakes NTS, IL
  "san-diego":    { lat: 32.74, lon: -117.20, tz: "America/Los_Angeles" }, // San Diego NTS
  "pearl-harbor": { lat: 21.36, lon: -157.95, tz: "Pacific/Honolulu"    }, // Pearl Harbor, HI
};

// 23 letters. Keep this in sync with letters.js — id, date, location_chapter.
const LETTERS = [
  { id: "L01", date: "1940-04-14", loc: "great-lakes" },
  { id: "L02", date: "1940-04-20", loc: "great-lakes" },
  { id: "L03", date: "1940-04-27", loc: "great-lakes" },
  { id: "L04", date: "1940-05-04", loc: "great-lakes" },
  { id: "L05", date: "1940-05-10", loc: "great-lakes" },
  { id: "L06", date: "1940-05-17", loc: "great-lakes" },
  { id: "L07", date: "1940-05-30", loc: "great-lakes" },
  { id: "L08", date: "1940-06-18", loc: "great-lakes" },
  { id: "L09", date: "1940-07-02", loc: "great-lakes" },
  { id: "L10", date: "1940-07-09", loc: "great-lakes" },
  { id: "L11", date: "1940-07-14", loc: "san-diego" },
  { id: "L12", date: "1940-07-19", loc: "san-diego" },
  { id: "L13", date: "1940-08-18", loc: "pearl-harbor" },
  { id: "L14", date: "1940-09-29", loc: "pearl-harbor" },
  { id: "L15", date: "1940-10-19", loc: "pearl-harbor" },
  { id: "L16", date: "1940-10-23", loc: "pearl-harbor" },
  { id: "L17", date: "1940-10-28", loc: "pearl-harbor" },
  { id: "L18", date: "1940-11-02", loc: "pearl-harbor" },
  { id: "L19", date: "1940-11-17", loc: "pearl-harbor" },
  { id: "L20", date: "1940-11-27", loc: "pearl-harbor" },
  { id: "L21", date: "1940-12-15", loc: "pearl-harbor" },
  { id: "L22", date: "1940-12-25", loc: "pearl-harbor" },
  { id: "L23", date: "1940-12-29", loc: "pearl-harbor" },
];

const ENDPOINT = "https://archive-api.open-meteo.com/v1/archive";

async function fetchOne({ id, date, loc }) {
  const { lat, lon, tz } = LOCATIONS[loc];
  const params = new URLSearchParams({
    latitude: String(lat),
    longitude: String(lon),
    start_date: date,
    end_date: date,
    daily: [
      "temperature_2m_max",
      "temperature_2m_min",
      "precipitation_sum",
      "snowfall_sum",
      "weathercode",
      "windspeed_10m_max",
    ].join(","),
    temperature_unit: "fahrenheit",
    precipitation_unit: "inch",
    windspeed_unit: "mph",
    timezone: tz,
  });
  const url = `${ENDPOINT}?${params.toString()}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${id} ${date} ${loc}: HTTP ${res.status} ${await res.text().catch(() => "")}`);
  }
  const j = await res.json();
  const d = j.daily || {};
  return {
    id,
    date,
    location: loc,
    tmax_f: d.temperature_2m_max?.[0] ?? null,
    tmin_f: d.temperature_2m_min?.[0] ?? null,
    precip_in: d.precipitation_sum?.[0] ?? null,
    snowfall_in: d.snowfall_sum?.[0] ?? null,
    wmo: d.weathercode?.[0] ?? null,
    wind_mph: d.windspeed_10m_max?.[0] ?? null,
  };
}

async function main() {
  console.log(`Fetching weather for ${LETTERS.length} letter dates from Open-Meteo …`);
  const results = {};
  for (const ltr of LETTERS) {
    try {
      const w = await fetchOne(ltr);
      results[ltr.id] = w;
      const t = w.tmax_f != null ? `${Math.round(w.tmin_f)}–${Math.round(w.tmax_f)}°F` : "—";
      console.log(`  ${ltr.id} ${ltr.date} ${ltr.loc.padEnd(13)}  WMO ${String(w.wmo).padStart(2)}  ${t}  ${w.precip_in ?? 0}″`);
      // be polite — small delay between requests
      await new Promise(r => setTimeout(r, 120));
    } catch (e) {
      console.error(`  ${ltr.id} FAILED:`, e.message);
      results[ltr.id] = { id: ltr.id, date: ltr.date, location: ltr.loc, error: String(e.message) };
    }
  }

  const out = `/* Generated by scripts/fetch_weather.mjs — do not edit by hand. */
window.LETTER_WEATHER = ${JSON.stringify(results, null, 2)};
`;
  const outPath = path.join(ROOT, "weather.js");
  await fs.writeFile(outPath, out);
  console.log(`\nWrote ${outPath}`);
}

main().catch(e => { console.error(e); process.exit(1); });
